### ISSUE TITLE
Make add-on for work Anki 2.1.x

### ISSUE THREAD

**Issue by Pradhyo** [Pradhyo/anki-markdown-notes#8]
Based on the [documentation](https://apps.ankiweb.net/docs/addons.html#porting-anki-2.0-add-ons), this shouldn't be too difficult.

**Comment by rmolin88** [comment]
I did some updates [here](https://github.com/rmolin88/anki_markdown_notes) to take care of this.
Thanks a lot for your work. Great plugin!

**Comment by michaelmagistro** [comment]
> I did some updates [here](https://github.com/rmolin88/anki_markdown_notes) to take care of this.
> Thanks a lot for your work. Great plugin!

I [forked this](https://github.com/michaelmagistro/anki_markdown_notes) and made some small adjustments for compatibility with Windows

**Comment by tricktux** [comment]
@michaelmagistro pull requests welcomed [here](https://github.com/rmolin88/anki_markdown_notes)
