### ISSUE TITLE
ImportError: No module named handlers

### ISSUE THREAD

**Issue by iwillbe** [Pradhyo/anki-markdown-notes#9]
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "C:\Users\User\AppData\Roaming\Anki2\addons\Anki_Markdown_Notes.py", line 8 , in <module>
    from logging.handlers import RotatingFileHandler
ImportError: No module named handlers

**Comment by Pradhyo** [comment]
Thank you.
This is related to #7 - I will fix both together when I get a chance.

**Comment by Pradhyo** [comment]
Sorry @iwillbe I just got a chance to upgrade the addon and also look into this issue.
I think [this commit](https://github.com/ankitects/anki/commit/c4eca03dd817c254c17334921c113ff0c2a9100b#diff-e080ac99773187385ef474e64f1d0d5172c6e4a9ee9a773544ac45ac24cb5844) should fix this issue, please reopen this issue if it still persists, thanks.
